ignoreFiles = ["content/portfolio/\\.*","content/product/\\.*","content/sketch/\\.*","content/homepage/\\.*","content/post/\\.*","content/\\.*"] # disable example pages as this is a single page
baseURL = "https://example.com/"
languageCode = "en-US"
title = "Bootstrap-BP hugo startpage"
theme = "bootstrap-bp-hugo-startpage"
# googleAnalytics = "UA-123-45"
copyright = "Sebastian Pech"
enableRobotsTXT = true
pygmentsCodeFences = true
canonifyurls = true
paginate = 5

[sitemap]
    changefreq = "weekly"
    priority = 0.5

[permalinks]
    posts = "/:year/:month/:slug/"
    post = "/:year/:month/:slug/"
    pages = "/:slug/"
    page = "/:slug/"

[Author]  
  name = "Sebastian Pech"

[params]
  description = "Text about the site"
  #images = ["logo.jpg"]
  startPageColumns = true
  welcomeText = "Bootstrap-BP hugo startpage"

[[params.searchEngines]]
  name = "Google"
  activated = true
  url = "https://www.google.com/search"

[[params.searchEngines]]
  name = "DuckDuckGo"
  activated = true
  url = "https://duckduckgo.com/"

[[params.searchEngines]]
  name = "Bing"
  activated = true
  url = "https://www.bing.com/search"

[taxonomies]
